---
title: "Bike Sharing Demand v.20"
author: "Tommy Ly"
date: "October 25, 2015"
output: html_document
---
# 1.Summarizing data
```{r,echo=FALSE}
getwd()
setwd('/Users/tommyly/Documents/MySlideRule/MySlideRule-Data-Science-Foundation/Bike Sharing Demand')
# Read the csv file
bike_train = read.csv("train.csv")
bike_test = read.csv("test.csv")
bike_test[c('casual', 'registered', 'count')] = 0 #reformat data so both are the same
bike_total = rbind(bike_train,bike_test) #cannot combine
# Structure of the dataset
str(bike_train)
str(bike_test)
str(bike_total)
# Statistical summary
summary(bike_train)
#Find missing value
table(is.na(bike_train)) #No N.A value. Awesome!
```

# 2. Basic Data Analysis
```{r,echo=FALSE}
#Vector notation
bike_train$count
# Finding the index of the time with highest rental
which.max(bike_train$count)
#Get name of all variables in dataset
names(bike_train)
## Get datetime/season/holiday/weather of the highest rental period
bike_train$datetime[9346]
bike_train$season[9346]
bike_train$holiday[9346]
bike_train$weather[9346]

```

#3.Exploratory Data Analysis 
```{r, echo=FALSE}

# by categorical variable
layout(matrix(c(1,1,2,3,4,5),2,3,byrow=FALSE)) #
boxplot(bike_train$count, main="count")
boxplot(bike_train$count ~ bike_train$weather, main="weather")
boxplot(bike_train$count ~ bike_train$season, main="season")
boxplot(bike_train$count ~ bike_train$holiday, main="holiday")
boxplot(bike_train$count ~ bike_train$workingday, main="working day")

#by numerical variable
par(mfrow=c(2,2))
par(mar = rep(2, 4))
hist(bike_train$humidity, main = "humidity")
hist(bike_train$temp, main = "temperature")
hist(bike_train$atemp, main = "feel temperature")

#Bivariate correlation
sub=data.frame(bike_train$registered,bike_train$casual,bike_train$count,bike_train$temp,bike_train$humidity,bike_train$atemp,bike_train$windspeed)
cor(sub)
```


#4.Reformatting data
```{r,echo=FALSE}
bike_train$season <- factor(bike_train$season, c(1,2,3,4), ordered=FALSE)
bike_train$holiday <- factor(bike_train$holiday, c(0,1), ordered=FALSE)
bike_train$workingday <- factor(bike_train$workingday, c(0,1), ordered=FALSE)
bike_train$weather <- factor(bike_train$weather, c(4,3,2,1), ordered=TRUE)
# set datetime ####
bike_train$datetime <- as.POSIXct(bike_train$datetime, format="%Y-%m-%d %H:%M:%S")
str(bike_train) #check if categorical have switched to factorial data

bike_test$season <- factor(bike_test$season, c(1,2,3,4), ordered=FALSE)
bike_test$holiday <- factor(bike_test$holiday, c(0,1), ordered=FALSE)
bike_test$workingday <- factor(bike_test$workingday, c(0,1), ordered=FALSE)
bike_test$weather <- factor(bike_test$weather, c(4,3,2,1), ordered=TRUE)
# set datetime ####
bike_test$datetime <- as.POSIXct(bike_test$datetime, format="%Y-%m-%d %H:%M:%S")
str(bike_test) #check if categorical have switched to factorial data
```

# 4.1 Feature Engineering
```{r,echo=FALSE}
#create time column by substring out timestamp
bike_train$time <- substring(bike_train$datetime,12,20)
bike_test$time <- substring(bike_test$datetime,12,20)
str(bike_train)

#create day of week column
bike_train$day <- weekdays(as.Date(bike_train$datetime))
bike_train$day <- as.factor(bike_train$day)
bike_test$day <- weekdays(as.Date(bike_test$datetime))
bike_test$day <- as.factor(bike_test$day)
str(bike_train)

#create Sunday variable
bike_train$sunday[bike_train$day == "Sunday"] <- "1"
bike_train$sunday[bike_train$day != "1"] <- "0"

bike_test$sunday[bike_test$day == "Sunday"] <- "1"
bike_test$sunday[bike_test$day != "1"] <- "0"

#convert to factor
bike_train$sunday <- as.factor(bike_train$sunday)
bike_test$sunday <- as.factor(bike_test$sunday)
str(bike_train)

#convert time and create $hour as integer to evaluate for daypart
bike_train$hour<- as.numeric(substr(bike_train$time,1,2))
bike_test$hour<- as.numeric(substr(bike_test$time,1,2))

#create daypart column, default to 4 to make things easier for ourselves
bike_train$daypart <- "4"
bike_test$daypart <- "4"


#4AM - 10AM = 1
bike_train$daypart[(bike_train$hour < 10) & (bike_train$hour > 3)] <- 1
bike_test$daypart[(bike_test$hour < 10) & (bike_test$hour > 3)] <- 1


#11AM - 3PM = 2
bike_train$daypart[(bike_train$hour < 16) & (bike_train$hour > 9)] <- 2
bike_test$daypart[(bike_test$hour < 16) & (bike_test$hour > 9)] <- 2


#4PM - 9PM = 3
bike_train$daypart[(bike_train$hour < 22) & (bike_train$hour > 15)] <- 3
bike_test$daypart[(bike_test$hour < 22) & (bike_test$hour > 15)] <- 3

#convert daypart to factor
bike_train$daypart <- as.factor(bike_train$daypart)
bike_test$daypart <- as.factor(bike_test$daypart)

#convert hour back to factor
bike_train$hour <- as.factor(bike_train$hour)
bike_test$hour <- as.factor(bike_test$hour)

```

# 7.1 Random Forest - Split Model for 2 Casual & Registered. 
```{r,echo=FALSE}
# Install rpart library
install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
install.packages('randomForest')
library(randomForest)

# Split the data
library(caTools)
set.seed(3000)
spl = sample.split(bike_train$count, SplitRatio = 0.7)
Train = subset(bike_train, spl==TRUE)
Test = subset(bike_train, spl==FALSE)

#Create log10 for casual & registered

Train$casual_log10=log10(Train$casual+1)
Train$registered_log10=log10(Train$registered+1)

#Build random forest model based on log10 value
BikeForest_Registered = randomForest(registered_log10 ~ season + weather + temp + humidity + windspeed + hour + sunday + daypart + sunday + holiday + workingday,data=Train[,-c(10)], ntree=250) 

BikeForest_Casual = randomForest(casual_log10 ~ season + weather + temp + humidity + 
windspeed + hour + sunday + daypart + sunday + holiday + workingday,data=Train[,-c(11)], ntree=250) 

PredictForest_Registered = predict(BikeForest_Registered, newdata = Test)

PredictForest_Casual = predict(BikeForest_Casual, newdata = Test)

PredictForest_Combine <- round(10^PredictForest_Registered + 10^PredictForest_Casual -2)

#Create evaluation function 
RMSLE_Evaluation <- function (data, pred) {
    return(sqrt(1/nrow(data)*sum((log(pred+1)-log(data$count+1))^2)))}

#Evaluate model
RMSLE_Evaluation(Test,PredictForest_Combine)

``````

